# Default configuration for DropUtils plugin
first-kill-message: '&d&lᴇɢɢ &8| &fYou killed the dragon for the first time, an egg has been dropped!'
give-egg: true
add-player-name: true
permission-command: 'lp user {player} permission set droputils.dragonegg true'
egg-item:
  name: '&d&lDragon Egg'
  lore: []
  player-lore: '&r&fPlayer: &#37bbe2{playername}'

# Settings for if give-egg is false.
drop-location:
  world: 'world'
  x: 0
  y: 80
  z: 0
