name: DropUtils
version: '1.0.0'
main: dev.infen.droputils
api-version: '1.21'
permissions:
  droputils.dragonegg:
    description: 'Marker permission applied after first dragon kill.'
    default: false
